import { useEffect, useState } from 'react'
import * as App from '../../../wailsjs/go/main/App'

// ---------------------------------------------------------------------------
// FridayPairingModal — Mac-side QR generator for the v0.3.0 Friday companion
// (TASK-025).
//
// The Friday phone app's pair.tsx (TASK-020) is a barcode scanner; this
// modal is its counterpart. Click "Connect Friday phone" in the
// ConnectionsPanel → modal opens → GenerateMobilePairingQR() returns a
// data-URL PNG → <img> renders it → user scans with Friday → done.
//
// Why a separate file (not inlined in ConnectionsPanel):
//   - ConnectionsPanel is already ~600 lines and adding another section
//     would push it past the modularity guideline.
//   - This component is purely visual + Wails-bound; extracting keeps the
//     parent focused on settings-config wiring.
//
// Style notes:
//   - Matches the existing AdvancedPanel modal pattern (holo-panel, cyan
//     accent #00e5ff, monospace footer, role="dialog" + aria-modal).
//   - Backdrop close on click; Escape closes via window keydown handler.
//   - "X" close button in the top-right corner.
// ---------------------------------------------------------------------------

// The GenerateMobilePairingQR binding is generated by `wails generate
// module` at build time from app_pairing.go (TASK-025). In CI/dev
// environments where the generated App.d.ts hasn't been regenerated yet
// after the Go side landed, the strict-mode TS compiler would refuse a
// static import. We bridge that with a runtime lookup against the
// namespace import + a typed alias — the binding always exists at
// runtime (the Go method is registered on App via the wails reflect
// loop); the typed alias keeps call sites type-safe. After the next
// `wails generate module` run, this pattern collapses to a direct named
// import without any test surface changing.
const GenerateMobilePairingQR =
  (App as unknown as { GenerateMobilePairingQR: () => Promise<string> }).GenerateMobilePairingQR

export interface FridayPairingModalProps {
  /** Controlled-open flag — parent decides when the modal is visible. */
  open: boolean
  /** Called when the user dismisses the modal (X click, backdrop, Escape). */
  onClose: () => void
}

// State machine for the QR fetch. Modeling this explicitly stops the UI
// from briefly showing a stale QR while a new fetch is in flight, and gives
// us a clean place to surface "no token configured" errors with the exact
// CTA the Go binding suggests.
type QrState =
  | { status: 'loading' }
  | { status: 'ready'; dataURL: string }
  | { status: 'error'; message: string }

export function FridayPairingModal({ open, onClose }: FridayPairingModalProps): React.ReactElement | null {
  const [qr, setQr] = useState<QrState>({ status: 'loading' })

  // Fetch the QR every time the modal opens. Closing + reopening regenerates
  // — useful in development where the mobile API port might have changed,
  // and harmless in production (the token is stable across opens).
  useEffect(() => {
    if (!open) return
    let cancelled = false
    setQr({ status: 'loading' })
    void (async () => {
      try {
        const dataURL = await GenerateMobilePairingQR()
        if (cancelled) return
        if (!dataURL || typeof dataURL !== 'string' || !dataURL.startsWith('data:image/')) {
          setQr({ status: 'error', message: 'QR payload was empty or malformed' })
          return
        }
        setQr({ status: 'ready', dataURL })
      } catch (e) {
        if (cancelled) return
        const msg = e instanceof Error ? e.message : String(e)
        setQr({ status: 'error', message: msg })
      }
    })()
    return () => {
      cancelled = true
    }
  }, [open])

  // Escape key closes the modal. We attach to window rather than the dialog
  // root so the handler fires even when focus is on the X button or the
  // backdrop has captured it.
  useEffect(() => {
    if (!open) return
    function onKey(e: KeyboardEvent): void {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open, onClose])

  if (!open) return null

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="friday-pair-title"
      data-testid="friday-pair-modal"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <div
        className="holo-panel p-6 max-w-md w-full relative"
        onClick={(e) => e.stopPropagation()}
      >
        {/* X close button — top-right corner. The hit target is comfortably
            large (28px) and aria-labeled for screen readers. */}
        <button
          type="button"
          onClick={onClose}
          aria-label="Close pairing dialog"
          data-testid="friday-pair-close"
          className="absolute top-3 right-3 w-7 h-7 flex items-center justify-center text-[#8ba4b8] hover:text-[#00e5ff] transition-colors"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>

        <h3 id="friday-pair-title" className="text-sm font-semibold text-[#00e5ff] mb-3 font-mono tracking-wide">
          Scan this with Friday
        </h3>

        {/* QR slot — fixed-size container so the layout doesn't jitter while
            loading. The image itself is 256x256; we render it at the same
            size on a light backdrop so dark-camera-side decoders don't
            struggle with low contrast. */}
        <div className="flex items-center justify-center my-2">
          <div className="w-[272px] h-[272px] flex items-center justify-center bg-white rounded p-2">
            {qr.status === 'loading' && (
              <span className="text-xs text-[#4a6278] font-mono" data-testid="friday-pair-loading">
                Generating QR…
              </span>
            )}
            {qr.status === 'error' && (
              <div className="text-center px-2" data-testid="friday-pair-error">
                <p className="text-xs text-red-500 font-mono mb-1">QR unavailable</p>
                <p className="text-[10px] text-[#4a6278] break-words">{qr.message}</p>
              </div>
            )}
            {qr.status === 'ready' && (
              <img
                src={qr.dataURL}
                alt="Pairing QR code — scan with the Friday app to connect this phone to Jarvis."
                width={256}
                height={256}
                data-testid="friday-pair-qr-img"
              />
            )}
          </div>
        </div>

        <p className="text-[11px] text-[#8ba4b8] font-mono text-center mt-3 leading-relaxed">
          Friday opens Expo Go → scans this QR → done.
        </p>
      </div>
    </div>
  )
}
