// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {workspace} from '../models';
import {config} from '../models';
import {discovery} from '../models';
import {nlquery} from '../models';
import {main} from '../models';
import {claude} from '../models';
import {agent} from '../models';
import {cmux} from '../models';
import {impact} from '../models';
import {jarvis} from '../models';
import {git} from '../models';
import {recording} from '../models';
import {setup} from '../models';
import {terminal} from '../models';
import {store} from '../models';

export function AddTaskToWorkflow(arg1:string,arg2:string):Promise<model.Task>;

export function AddToSessionGroup(arg1:string,arg2:string):Promise<void>;

export function BroadcastCommand(arg1:Array<number>,arg2:string):Promise<Record<number, string>>;

export function BroadcastToAll(arg1:string):Promise<Record<number, string>>;

export function BrowseForDirectory(arg1:string):Promise<string>;

export function CreateRecipe(arg1:string,arg2:Array<model.TemplateParam>,arg3:Array<model.RecipeStep>):Promise<model.SessionTemplate>;

export function CreateSessionGroup(arg1:string,arg2:string,arg3:string):Promise<model.SessionGroup>;

export function CreateSessionTodo(arg1:string,arg2:string):Promise<model.SessionTodo>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Task>;

export function CreateWorkflow(arg1:string,arg2:string):Promise<model.Workflow>;

export function CreateWorkspace(arg1:string,arg2:Array<string>,arg3:string):Promise<workspace.Workspace>;

export function CreateWorkspaceAndLaunch(arg1:string,arg2:Array<string>,arg3:string):Promise<workspace.Workspace>;

export function DaemonRestartNeeded(arg1:config.Config,arg2:config.Config):Promise<boolean>;

export function DeleteSavedProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSessionGroup(arg1:string):Promise<void>;

export function DeleteSessionTemplate(arg1:string):Promise<void>;

export function DeleteSessionTodo(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DiscoverProjects():Promise<Array<discovery.Project>>;

export function ExecuteDivideAndConquer(arg1:string,arg2:Array<string>,arg3:string,arg4:boolean):Promise<void>;

export function ExecuteNLQuery(arg1:string):Promise<nlquery.QueryResult>;

export function ExecuteWorkflow(arg1:Array<main.WorkflowPhase>):Promise<void>;

export function ExportConfig():Promise<string>;

export function FocusCMuxSurface(arg1:string):Promise<void>;

export function FocusSession(arg1:number):Promise<void>;

export function FocusTerminalWindow(arg1:string):Promise<void>;

export function ForkSession(arg1:string):Promise<model.Session>;

export function GetActiveSessions():Promise<Array<model.Session>>;

export function GetActivityFeed(arg1:number,arg2:string):Promise<Array<model.ActivityEvent>>;

export function GetAllCosts():Promise<Array<claude.SessionUsage>>;

export function GetAudioInputDevices():Promise<Array<main.AudioDevice>>;

export function GetAutoDetectedCount():Promise<number>;

export function GetAvailableAgents():Promise<Array<agent.AgentInfo>>;

export function GetAvailableTerminals():Promise<Array<string>>;

export function GetCMuxSurfaces():Promise<Array<cmux.Surface>>;

export function GetCMuxWorkspaces():Promise<Array<cmux.Workspace>>;

export function GetClaudeSessions():Promise<Array<claude.Session>>;

export function GetConfig():Promise<config.Config>;

export function GetDailyCostSummary():Promise<Array<model.DailyCost>>;

export function GetDashboardStats():Promise<model.DashboardStats>;

export function GetDiagnostics():Promise<main.DiagnosticsSnapshot>;

export function GetImpactWarnings():Promise<Array<impact.ImpactWarning>>;

export function GetJarvisHistory():Promise<Array<jarvis.Message>>;

export function GetJarvisState():Promise<string>;

export function GetMicPermissionStatus():Promise<string>;

export function GetMobileConnectionInfo():Promise<main.MobileConnectionInfo>;

export function GetPendingApprovals():Promise<Array<model.ApprovalRequest>>;

export function GetProjectCosts(arg1:string):Promise<Array<claude.SessionUsage>>;

export function GetProjectSuggestions(arg1:string):Promise<Array<discovery.TaskSuggestion>>;

export function GetRecipeWithDetails(arg1:string):Promise<Record<string, any>>;

export function GetRepoDiff(arg1:string):Promise<git.DiffResult>;

export function GetRepoInfo(arg1:string):Promise<git.RepoInfo>;

export function GetRunningTasks():Promise<Array<model.Task>>;

export function GetSession(arg1:string):Promise<model.Session>;

export function GetSessionDiff(arg1:number):Promise<git.DiffResult>;

export function GetSessionGroupMembers(arg1:string):Promise<Array<model.GroupMember>>;

export function GetSessionIndicators():Promise<Array<claude.SessionIndicator>>;

export function GetSessionRecording(arg1:string):Promise<Array<recording.Snapshot>>;

export function GetSessionTerminalOutput(arg1:number):Promise<string>;

export function GetSessionTodos(arg1:string):Promise<Array<model.SessionTodo>>;

export function GetSetupState():Promise<setup.SetupState>;

export function GetStagedDiff(arg1:string):Promise<git.DiffResult>;

export function GetTask(arg1:string):Promise<model.Task>;

export function GetTaskActivity(arg1:string,arg2:number):Promise<Array<model.ActivityEvent>>;

export function GetTaskDiff(arg1:string):Promise<git.DiffResult>;

export function GetTaskGitInfo(arg1:string):Promise<git.RepoInfo>;

export function GetTaskOutput(arg1:string,arg2:number):Promise<Array<string>>;

export function GetTasks(arg1:string):Promise<Array<model.Task>>;

export function GetTasksGroupedByRepo():Promise<Record<string, Array<model.Task>>>;

export function GetTerminalWindows():Promise<Array<terminal.TerminalWindow>>;

export function GetTotalSpend():Promise<model.TotalSpend>;

export function GetWorkflowTasks(arg1:string):Promise<Array<model.Task>>;

export function GetWorkflows():Promise<Array<model.Workflow>>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<void>;

export function GitDiscardFile(arg1:string,arg2:string):Promise<void>;

export function GitPush(arg1:string):Promise<void>;

export function GitStageAll(arg1:string):Promise<void>;

export function GitStageFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function GitStash(arg1:string,arg2:string):Promise<void>;

export function GitStashApply(arg1:string,arg2:number):Promise<void>;

export function GitStashDrop(arg1:string,arg2:number):Promise<void>;

export function GitStashList(arg1:string):Promise<Array<git.StashEntry>>;

export function ImportConfig(arg1:string,arg2:boolean):Promise<void>;

export function IsCMuxAvailable():Promise<boolean>;

export function IsFirstRun():Promise<boolean>;

export function IsJarvisDaemonConnected():Promise<boolean>;

export function IsOllamaRunning():Promise<boolean>;

export function IsSetupComplete():Promise<boolean>;

export function LaunchFromTemplate(arg1:string):Promise<void>;

export function LaunchReposInTerminal(arg1:Array<string>,arg2:string,arg3:Array<boolean>):Promise<void>;

export function LaunchReposInTerminalWithWorktree(arg1:Array<string>,arg2:string,arg3:boolean):Promise<void>;

export function LaunchSession(arg1:string,arg2:string,arg3:string):Promise<model.Session>;

export function ListRecordedSessions():Promise<Array<recording.RecordingSummary>>;

export function ListSavedProjects():Promise<Array<store.Project>>;

export function ListSessionGroups():Promise<Array<model.SessionGroup>>;

export function ListSessionTemplates():Promise<Array<model.SessionTemplate>>;

export function ListSessions(arg1:string):Promise<Array<model.Session>>;

export function ListWorkspaces():Promise<Array<workspace.Workspace>>;

export function MarkFirstRunComplete():Promise<void>;

export function OpenApp(arg1:string):Promise<void>;

export function OpenDaemonLog():Promise<void>;

export function OpenFileForImport():Promise<string>;

export function OpenPRInBrowser(arg1:string):Promise<void>;

export function OpenSetupLog():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenWorkspaceInTerminal(arg1:string):Promise<void>;

export function PreviewVoice(arg1:string,arg2:string):Promise<void>;

export function QueueSession(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<model.Session>;

export function ReadFromCMux(arg1:string):Promise<string>;

export function ReadFromTerminal(arg1:string):Promise<string>;

export function RegenerateMobileToken():Promise<void>;

export function RemoveFromSessionGroup(arg1:string,arg2:string):Promise<void>;

export function RemoveTaskFromWorkflow(arg1:string):Promise<model.Task>;

export function RequestMicPermission():Promise<void>;

export function ResetConfig(arg1:boolean):Promise<void>;

export function RespondToApproval(arg1:number,arg2:string):Promise<void>;

export function RestartJarvis():Promise<void>;

export function ResumeSession(arg1:string):Promise<model.Session>;

export function RunSetup():Promise<setup.SetupState>;

export function SaveConfig(arg1:config.Config):Promise<config.SaveResult>;

export function SaveProject(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveSessionTemplate(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<model.SessionTemplate>;

export function ScanNow():Promise<number>;

export function SearchOutput(arg1:string):Promise<Array<store.OutputSearchResult>>;

export function SearchRepos(arg1:string):Promise<Array<discovery.RepoSearchResult>>;

export function SendCommandToSession(arg1:number,arg2:string):Promise<void>;

export function SendJarvisCommand(arg1:string):Promise<void>;

export function SendJarvisMessage(arg1:string):Promise<string>;

export function SendSessionMessage(arg1:string,arg2:string):Promise<void>;

export function SendToCMux(arg1:string,arg2:string):Promise<void>;

export function SendToTerminal(arg1:string,arg2:string):Promise<void>;

export function SetDotClaudeSource(arg1:string):Promise<void>;

export function SetJarvisConfig(arg1:jarvis.JarvisConfig):Promise<void>;

export function StartJarvis():Promise<void>;

export function StopAllWatchers():Promise<void>;

export function StopJarvis():Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function StopWatchingOutput(arg1:string):Promise<void>;

export function SuggestWorkflows():Promise<Array<main.WorkflowSuggestion>>;

export function SyncDotClaude():Promise<number>;

export function UpdateSessionTodo(arg1:string,arg2:string):Promise<void>;

export function UpdateTaskOutputPath(arg1:string,arg2:string):Promise<model.Task>;

export function UpdateTaskStatus(arg1:string,arg2:string):Promise<model.Task>;

export function ValidateAPIKey(arg1:string,arg2:string):Promise<main.APIKeyValidationResult>;

export function WatchTaskOutput(arg1:string):Promise<void>;
