// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTaskToWorkflow(arg1, arg2) {
  return window['go']['main']['App']['AddTaskToWorkflow'](arg1, arg2);
}

export function AddToSessionGroup(arg1, arg2) {
  return window['go']['main']['App']['AddToSessionGroup'](arg1, arg2);
}

export function BroadcastCommand(arg1, arg2) {
  return window['go']['main']['App']['BroadcastCommand'](arg1, arg2);
}

export function BroadcastToAll(arg1) {
  return window['go']['main']['App']['BroadcastToAll'](arg1);
}

export function BrowseForDirectory(arg1) {
  return window['go']['main']['App']['BrowseForDirectory'](arg1);
}

export function CreateRecipe(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRecipe'](arg1, arg2, arg3);
}

export function CreateSessionGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSessionGroup'](arg1, arg2, arg3);
}

export function CreateSessionTodo(arg1, arg2) {
  return window['go']['main']['App']['CreateSessionTodo'](arg1, arg2);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function CreateWorkflow(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkflow'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3);
}

export function CreateWorkspaceAndLaunch(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspaceAndLaunch'](arg1, arg2, arg3);
}

export function DeleteSavedProject(arg1) {
  return window['go']['main']['App']['DeleteSavedProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSessionGroup(arg1) {
  return window['go']['main']['App']['DeleteSessionGroup'](arg1);
}

export function DeleteSessionTemplate(arg1) {
  return window['go']['main']['App']['DeleteSessionTemplate'](arg1);
}

export function DeleteSessionTodo(arg1) {
  return window['go']['main']['App']['DeleteSessionTodo'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DiscoverProjects() {
  return window['go']['main']['App']['DiscoverProjects']();
}

export function ExecuteDivideAndConquer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteDivideAndConquer'](arg1, arg2, arg3, arg4);
}

export function ExecuteNLQuery(arg1) {
  return window['go']['main']['App']['ExecuteNLQuery'](arg1);
}

export function ExecuteWorkflow(arg1) {
  return window['go']['main']['App']['ExecuteWorkflow'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function FocusCMuxSurface(arg1) {
  return window['go']['main']['App']['FocusCMuxSurface'](arg1);
}

export function FocusSession(arg1) {
  return window['go']['main']['App']['FocusSession'](arg1);
}

export function FocusTerminalWindow(arg1) {
  return window['go']['main']['App']['FocusTerminalWindow'](arg1);
}

export function ForkSession(arg1) {
  return window['go']['main']['App']['ForkSession'](arg1);
}

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetActivityFeed(arg1, arg2) {
  return window['go']['main']['App']['GetActivityFeed'](arg1, arg2);
}

export function GetAllCosts() {
  return window['go']['main']['App']['GetAllCosts']();
}

export function GetAudioInputDevices() {
  return window['go']['main']['App']['GetAudioInputDevices']();
}

export function GetAutoDetectedCount() {
  return window['go']['main']['App']['GetAutoDetectedCount']();
}

export function GetAvailableAgents() {
  return window['go']['main']['App']['GetAvailableAgents']();
}

export function GetAvailableTerminals() {
  return window['go']['main']['App']['GetAvailableTerminals']();
}

export function GetCMuxSurfaces() {
  return window['go']['main']['App']['GetCMuxSurfaces']();
}

export function GetCMuxWorkspaces() {
  return window['go']['main']['App']['GetCMuxWorkspaces']();
}

export function GetClaudeSessions() {
  return window['go']['main']['App']['GetClaudeSessions']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDailyCostSummary() {
  return window['go']['main']['App']['GetDailyCostSummary']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetImpactWarnings() {
  return window['go']['main']['App']['GetImpactWarnings']();
}

export function GetJarvisHistory() {
  return window['go']['main']['App']['GetJarvisHistory']();
}

export function GetJarvisState() {
  return window['go']['main']['App']['GetJarvisState']();
}

export function GetMicPermissionStatus() {
  return window['go']['main']['App']['GetMicPermissionStatus']();
}

export function GetMobileConnectionInfo() {
  return window['go']['main']['App']['GetMobileConnectionInfo']();
}

export function GetPendingApprovals() {
  return window['go']['main']['App']['GetPendingApprovals']();
}

export function GetProjectCosts(arg1) {
  return window['go']['main']['App']['GetProjectCosts'](arg1);
}

export function GetProjectSuggestions(arg1) {
  return window['go']['main']['App']['GetProjectSuggestions'](arg1);
}

export function GetRecipeWithDetails(arg1) {
  return window['go']['main']['App']['GetRecipeWithDetails'](arg1);
}

export function GetRepoDiff(arg1) {
  return window['go']['main']['App']['GetRepoDiff'](arg1);
}

export function GetRepoInfo(arg1) {
  return window['go']['main']['App']['GetRepoInfo'](arg1);
}

export function GetRunningTasks() {
  return window['go']['main']['App']['GetRunningTasks']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessionDiff(arg1) {
  return window['go']['main']['App']['GetSessionDiff'](arg1);
}

export function GetSessionGroupMembers(arg1) {
  return window['go']['main']['App']['GetSessionGroupMembers'](arg1);
}

export function GetSessionIndicators() {
  return window['go']['main']['App']['GetSessionIndicators']();
}

export function GetSessionRecording(arg1) {
  return window['go']['main']['App']['GetSessionRecording'](arg1);
}

export function GetSessionTerminalOutput(arg1) {
  return window['go']['main']['App']['GetSessionTerminalOutput'](arg1);
}

export function GetSessionTodos(arg1) {
  return window['go']['main']['App']['GetSessionTodos'](arg1);
}

export function GetStagedDiff(arg1) {
  return window['go']['main']['App']['GetStagedDiff'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskActivity(arg1, arg2) {
  return window['go']['main']['App']['GetTaskActivity'](arg1, arg2);
}

export function GetTaskDiff(arg1) {
  return window['go']['main']['App']['GetTaskDiff'](arg1);
}

export function GetTaskGitInfo(arg1) {
  return window['go']['main']['App']['GetTaskGitInfo'](arg1);
}

export function GetTaskOutput(arg1, arg2) {
  return window['go']['main']['App']['GetTaskOutput'](arg1, arg2);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function GetTasksGroupedByRepo() {
  return window['go']['main']['App']['GetTasksGroupedByRepo']();
}

export function GetTerminalWindows() {
  return window['go']['main']['App']['GetTerminalWindows']();
}

export function GetTotalSpend() {
  return window['go']['main']['App']['GetTotalSpend']();
}

export function GetWorkflowTasks(arg1) {
  return window['go']['main']['App']['GetWorkflowTasks'](arg1);
}

export function GetWorkflows() {
  return window['go']['main']['App']['GetWorkflows']();
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitDiscardFile(arg1, arg2) {
  return window['go']['main']['App']['GitDiscardFile'](arg1, arg2);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitStageAll(arg1) {
  return window['go']['main']['App']['GitStageAll'](arg1);
}

export function GitStageFiles(arg1, arg2) {
  return window['go']['main']['App']['GitStageFiles'](arg1, arg2);
}

export function GitStash(arg1, arg2) {
  return window['go']['main']['App']['GitStash'](arg1, arg2);
}

export function GitStashApply(arg1, arg2) {
  return window['go']['main']['App']['GitStashApply'](arg1, arg2);
}

export function GitStashDrop(arg1, arg2) {
  return window['go']['main']['App']['GitStashDrop'](arg1, arg2);
}

export function GitStashList(arg1) {
  return window['go']['main']['App']['GitStashList'](arg1);
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2);
}

export function IsCMuxAvailable() {
  return window['go']['main']['App']['IsCMuxAvailable']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsJarvisDaemonConnected() {
  return window['go']['main']['App']['IsJarvisDaemonConnected']();
}

export function IsOllamaRunning() {
  return window['go']['main']['App']['IsOllamaRunning']();
}

export function LaunchFromTemplate(arg1) {
  return window['go']['main']['App']['LaunchFromTemplate'](arg1);
}

export function LaunchReposInTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchReposInTerminal'](arg1, arg2, arg3);
}

export function LaunchReposInTerminalWithWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchReposInTerminalWithWorktree'](arg1, arg2, arg3);
}

export function LaunchSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchSession'](arg1, arg2, arg3);
}

export function ListRecordedSessions() {
  return window['go']['main']['App']['ListRecordedSessions']();
}

export function ListSavedProjects() {
  return window['go']['main']['App']['ListSavedProjects']();
}

export function ListSessionGroups() {
  return window['go']['main']['App']['ListSessionGroups']();
}

export function ListSessionTemplates() {
  return window['go']['main']['App']['ListSessionTemplates']();
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function MarkFirstRunComplete() {
  return window['go']['main']['App']['MarkFirstRunComplete']();
}

export function OpenApp(arg1) {
  return window['go']['main']['App']['OpenApp'](arg1);
}

export function OpenFileForImport() {
  return window['go']['main']['App']['OpenFileForImport']();
}

export function OpenPRInBrowser(arg1) {
  return window['go']['main']['App']['OpenPRInBrowser'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function OpenWorkspaceInTerminal(arg1) {
  return window['go']['main']['App']['OpenWorkspaceInTerminal'](arg1);
}

export function PreviewVoice(arg1, arg2) {
  return window['go']['main']['App']['PreviewVoice'](arg1, arg2);
}

export function QueueSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['QueueSession'](arg1, arg2, arg3, arg4, arg5);
}

export function ReadFromCMux(arg1) {
  return window['go']['main']['App']['ReadFromCMux'](arg1);
}

export function ReadFromTerminal(arg1) {
  return window['go']['main']['App']['ReadFromTerminal'](arg1);
}

export function RegenerateMobileToken() {
  return window['go']['main']['App']['RegenerateMobileToken']();
}

export function RemoveFromSessionGroup(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromSessionGroup'](arg1, arg2);
}

export function RemoveTaskFromWorkflow(arg1) {
  return window['go']['main']['App']['RemoveTaskFromWorkflow'](arg1);
}

export function RequestMicPermission() {
  return window['go']['main']['App']['RequestMicPermission']();
}

export function ResetConfig(arg1) {
  return window['go']['main']['App']['ResetConfig'](arg1);
}

export function RespondToApproval(arg1, arg2) {
  return window['go']['main']['App']['RespondToApproval'](arg1, arg2);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2, arg3);
}

export function SaveSessionTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSessionTemplate'](arg1, arg2, arg3, arg4);
}

export function ScanNow() {
  return window['go']['main']['App']['ScanNow']();
}

export function SearchOutput(arg1) {
  return window['go']['main']['App']['SearchOutput'](arg1);
}

export function SearchRepos(arg1) {
  return window['go']['main']['App']['SearchRepos'](arg1);
}

export function SendCommandToSession(arg1, arg2) {
  return window['go']['main']['App']['SendCommandToSession'](arg1, arg2);
}

export function SendJarvisCommand(arg1) {
  return window['go']['main']['App']['SendJarvisCommand'](arg1);
}

export function SendJarvisMessage(arg1) {
  return window['go']['main']['App']['SendJarvisMessage'](arg1);
}

export function SendSessionMessage(arg1, arg2) {
  return window['go']['main']['App']['SendSessionMessage'](arg1, arg2);
}

export function SendToCMux(arg1, arg2) {
  return window['go']['main']['App']['SendToCMux'](arg1, arg2);
}

export function SendToTerminal(arg1, arg2) {
  return window['go']['main']['App']['SendToTerminal'](arg1, arg2);
}

export function SetDotClaudeSource(arg1) {
  return window['go']['main']['App']['SetDotClaudeSource'](arg1);
}

export function SetJarvisConfig(arg1) {
  return window['go']['main']['App']['SetJarvisConfig'](arg1);
}

export function StartJarvis() {
  return window['go']['main']['App']['StartJarvis']();
}

export function StopAllWatchers() {
  return window['go']['main']['App']['StopAllWatchers']();
}

export function StopJarvis() {
  return window['go']['main']['App']['StopJarvis']();
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function StopWatchingOutput(arg1) {
  return window['go']['main']['App']['StopWatchingOutput'](arg1);
}

export function SuggestWorkflows() {
  return window['go']['main']['App']['SuggestWorkflows']();
}

export function SyncDotClaude() {
  return window['go']['main']['App']['SyncDotClaude']();
}

export function UpdateSessionTodo(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionTodo'](arg1, arg2);
}

export function UpdateTaskOutputPath(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskOutputPath'](arg1, arg2);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}

export function ValidateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ValidateAPIKey'](arg1, arg2);
}

export function WatchTaskOutput(arg1) {
  return window['go']['main']['App']['WatchTaskOutput'](arg1);
}
